//
//  MyStyleKitName.h
//  InkedMargin
//
//  Created by Alok Pandey on 26/02/16.
//  Copyright (c) 2016 Alok . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface MyStyleKitName : NSObject

// Colors
+ (NSColor*)yelloColorActive;

// Drawing Methods
+ (void)drawDropView;
+ (void)drawDropViewOnKindleConnectedWithFrame: (NSRect)frame;
+ (void)drawFavouriteIconSidebarWithFrame: (NSRect)frame isStarActive: (BOOL)isStarActive;
+ (void)drawFavouriteIconMainWithFrame: (NSRect)frame isStarActive: (BOOL)isStarActive;
+ (void)drawAuthorIcon;
+ (void)drawCanvas3;
+ (void)drawInkedMargin512pt;
+ (void)drawInkedMargin256pt;
+ (void)drawInkedMargin128pt;
+ (void)drawInkedMargin32pt;
+ (void)drawInkedMargin16pt;
+ (void)drawEmptyDatabaseView;

// Generated Images
+ (NSImage*)imageOfDropView;
+ (NSImage*)imageOfDropViewOnKindleConnectedWithFrame: (NSRect)frame;
+ (NSImage*)imageOfFavouriteIconSidebarWithFrame: (NSRect)frame isStarActive: (BOOL)isStarActive;
+ (NSImage*)imageOfFavouriteIconMainWithFrame: (NSRect)frame isStarActive: (BOOL)isStarActive;
+ (NSImage*)imageOfAuthorIcon;
+ (NSImage*)imageOfStarSideBarIcon;
+ (NSImage*)imageOfTrashSideBarIcon;
+ (NSImage*)imageOfRecentelyAddedIcon;

@end
